import type { TaxRules } from '../../shared/tax-rules'
import {
  COMPREHENSIVE_BASIC_DEDUCTIONS_FROM_2027,
  COMPREHENSIVE_CALCULATED_TAX_MINIMUM_FROM_2027,
  COMPREHENSIVE_FAIR_MARKET_VALUE_RATIOS_2027,
  COMPREHENSIVE_PAYABLE_TAX_MINIMUM_FROM_2027,
  COMPREHENSIVE_TAX_BRACKETS_2027_UP_TO_TWO_HOMES,
  COMPREHENSIVE_TAX_COMMON_RULES,
  COMPREHENSIVE_TAX_REFORM_UNIFIED_BRACKETS,
  COMPREHENSIVE_TAXABLE_THRESHOLDS_FROM_2027,
} from './comprehensive-tax'
import {
  COMPREHENSIVE_TAX_BURDEN_CAP_RULES_FROM_2027,
} from './comprehensive-tax-burden-cap'
import {
  COMPREHENSIVE_TAX_CREDIT_RULES_2027,
} from './comprehensive-tax-credit'
import { PROPERTY_TAX_RULES_2027 } from './property-tax'
import {
  TRANSFER_BASIC_DEDUCTIONS_FROM_2027,
  TRANSFER_LONG_TERM_DEDUCTIONS_THROUGH_2027,
} from './transfer-deductions'
import { TRANSFER_TAX_COMMON_RULES } from './transfer-tax-common'

export const TAX_RULES_2027 = {
  year: 2027,
  propertyTax: PROPERTY_TAX_RULES_2027,
  comprehensiveTax: {
    ...COMPREHENSIVE_TAX_COMMON_RULES,
    taxableThresholds: COMPREHENSIVE_TAXABLE_THRESHOLDS_FROM_2027,
    basicDeductions: COMPREHENSIVE_BASIC_DEDUCTIONS_FROM_2027,
    fairMarketValueRatios: COMPREHENSIVE_FAIR_MARKET_VALUE_RATIOS_2027,
    calculatedTaxMinimum:
      COMPREHENSIVE_CALCULATED_TAX_MINIMUM_FROM_2027,
    payableTaxMinimum: COMPREHENSIVE_PAYABLE_TAX_MINIMUM_FROM_2027,
    brackets: {
      kind: 'byHomeCount',
      upToTwoHomes: COMPREHENSIVE_TAX_BRACKETS_2027_UP_TO_TWO_HOMES,
      threeOrMoreHomes: COMPREHENSIVE_TAX_REFORM_UNIFIED_BRACKETS,
    },
    taxCredit: COMPREHENSIVE_TAX_CREDIT_RULES_2027,
    taxBurdenCap: COMPREHENSIVE_TAX_BURDEN_CAP_RULES_FROM_2027,
  },
  transferTax: {
    ...TRANSFER_TAX_COMMON_RULES,
    longTermDeductions: TRANSFER_LONG_TERM_DEDUCTIONS_THROUGH_2027,
    deductionCaps: null,
    basicDeductions: TRANSFER_BASIC_DEDUCTIONS_FROM_2027,
  },
} as const satisfies TaxRules
