name = "incometax"
main = "worker/index.ts"
compatibility_date = "2026-08-04"

[assets]
directory = "./dist"

[[kv_namespaces]]
binding = "LDONG"
id = "44ac6675379f452d976b9ea9c5ebe24a"
preview_id = "92a68cc4a68e45a4abef51d80ae47274"

[triggers]
crons = ["0 19 * * *"]

[[d1_databases]]
binding = "COMPLEX_DB"
migrations_dir = "migrations"
